server:
  port: 9527
spring:
  application:
    name: micro-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gatewat-9527.com
    prefer-ip-address: true
zuul:
  prefix: /lwhtarena
  ignored-services: "*"
  routes:
    mydept.serviceId: micro-provider-dept
    mydept.path: /mydept/**

info:
  app.name: micro-cloud
  company.name: www.lwhtarena.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$