server:
  port: 8001

spring:
  application:
    name: cloud-providor-hystrix-payment

eureka:
  client:
    register-with-eureka: true #标识不向注册中心注册自己
    fetch-registry: true #表示自己就是注册中西，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka



