server:
  port: 3344

spring:
  application:
    name: micro-config-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LWHTarena/cloud-center-config.git #GitHub上面的git仓库名字