server:
  port: 8761
spring:
  application:
    name: eureka
### 注册中心配置
eureka:
  instance:
    #eureka实例主机名称
    hostname: eureka-center
    prefer-ip-address: true

  #客户端进行Eureka注册的配置
  client:
    # 当 Eureka Server 不可用时，这时就获取不到 注册列表，当从此类进行获取注册列表
    register-with-eureka: false
    # 注册中心职责是维护服务实例，false：不检索服务。
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/euraka/
  #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false