server:
  port: 8080
spring:
  redis:
    host: 192.168.56.15
    port: 6379
    password: tarena
    database: 1
    lettuce:
      pool:
        max-idle: 8 #连接池中的大空闲连接
        min-idle: 0 #连接池中的大空闲连接
        max-active: 200 #连接池大连接数（使用负值表示没有限制）
        max-wait: -1 #获取连接的最大等待时间，默认-1，表示无限制，单位毫秒。默认值可能会因为获取不到连接，导致事务无法提交，数据库被锁，大量线程处于等待状态的情况。
    timeout: 10000ms #连接超时时间（毫秒）

