nacos-server-addr: 192.168.56.15:8848
nacos-namespace: 4a44b565-609d-4cd8-8329-6dc655dd1f72
nacos-seata-group: SEATA_GROUP

server:
  port: 8083
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.15:3306/seata_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 30000
      maximum-pool-size: 15
      max-lifetime: 0
      minimum-idle: 5
      pool-name: DateBookHikariCP
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-server-addr} #配置注册中心
        namespace: ${nacos-namespace}
        group: ${nacos-seata-group}

mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug
seata:
  enabled: true #开启自动装配
  application-id: ${spring.application.name} #本客户端的微服务名称
  tx-service-group: my_test_tx_group #读取那个事务分组
  #配置注册中心
  registry:
    type: nacos
    nacos:
      cluster: seata-server-cluster
      application: seata-server #SEATA TC服务中心的微服务名，此处与服务保持一致
      server-addr: ${nacos-server-addr}
      namespace: ${nacos-namespace}
      group: ${nacos-seata-group}
  #配置服务中心
  config:
    type: nacos
    nacos:
      server-addr: ${nacos-server-addr}
      namespace: ${nacos-namespace}
      group: ${nacos-seata-group}

#这里有个巨大的坑 seata.enableAutoDataSourceProxy 这个配置写在，yaml 文件里
#的时候，智能提示的配置项是enable-auto-data-source-proxy，无法生效。必须写为
#enableAutoDataSourceProxy 的形式。
#智能提示给出的设置，无法生效
#seata:
#  enable-auto-data-source-proxy: false
#正常生效的例子
#seata:
#  enableAutoDataSourceProxy: false
#  application-id: test_tx_group
#  tx-service-group: test_tx_group
#  service:
#    vgroup-mapping:
#      test_tx_group: seata_tc_server
#    #配置Client连接TC的地址
##    grouplist: "192.168.56.15:8091"
#    #是否禁用全局事务
#    disable-global-transaction: false

