# Server settings
server:
  port: 8765

## 自定义磁盘目录
web:
  upload-path: /var/log/cloud-upgrade/
  sqliteDB: /var/log/winhong-pxe/

# DataSource settings 配置数据库的连接方式
#spring:
#  mvc:
#    favicon:
#      enabled: false
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

# Logger settings
#logging:
#  file: /var/log/winhong-pxe/winhong-pxe.log
#  level: info
#  pattern:
#    level: com.lwhtarena.pxe

## mybatis 配置




#mybatis:
#  type-aliases-package: com.lwhtarena.sqlite.domain
#  mapper-locations: classpath:com/lwhtarena/sqlite/domain/mapper/*.xml
